### ISSUE TITLE
CAs

### ISSUE THREAD

**Issue by SteveMarquess** [mattcaswell/ossl-book#1]
Section 2.1 introduces the concept of a root certificate in a simplistic way:

"Having obtained a private/public key pair a server operator will apply to a
third party organisation, known as a Certificate Authority (CA) for a certifi-
cate."

That is indeed the common perception, that the root certificates owned by proprietary companies and bundled with popular browsers, and server certificates signed by them, are somehow special. That isn't entirely true, and in some circumstances an organization would be wise to sign their server certs with a root cert that they own and control exclusively.

At this introductory stage of the book that's too much complexity to get into (the whole x.509 "spaghetti of doubt" thing). But, I think this first mention of root certs should just note, for now, that a certificate is created from the private/public key pair. The footnote can state that this can be done with a rook certificate by the server operator or (most commonly) via a commercial CA. That way we don't reinforce a common misperception.

**Comment by mattcaswell** [comment]
I wasn't sure from your description above whether you meant that we should not mention CAs at all. Or just not get into the whole "is it an external commercial organisation", or some "internal CA" debate. I think we do need to have some mention of CAs here, because that understanding is needed for chapter 3.

I have amended the wording to remove the reference to a third party organisation in the main text. So it now says:

```
Having obtained a private/public key pair a server operator must obtain their
certificate from a Certificate Authority (CA).
The CA will, at a minimum, verify that the server 
operator is in control of the domain name to be included in the certificate. 
Dependant on the type of certificate ordered, other checks may also be 
performed to verify the identity of the server operator. Finally the CA will 
issue the certificate which itself will be digitally signed by the CA.
```

There is also a footnote which says:

```
CAs can be
privately run and purely internal to an organisation; or they could be public.
Which type is most appropriate will depend on what the certificte will be used
for. There are many public CAs available. A simple search in your search engine
of choice should turn up lots of links. Most charge a fee for
issuing a certificate.
```

Does that address your concern?

**Comment by SteveMarquess** [comment]
On 10/28/2015 12:28 PM, mattcaswell wrote:

> I wasn't sure from your description above whether you meant that we
> should not mention CAs at all. Or just not get into the whole "is it an
> external commercial organisation", or some "internal CA" debate. I think
> we do need to have some mention of CAs here, because that understanding
> is needed for chapter 3.
> 
> I have amended the wording to remove the reference to a third party
> organisation in the main text. So it now says:
> 
> |Having obtained a private/public key pair a server operator must obtain
> their certificate from a Certificate Authority (CA). The CA will, at a
> minimum, verify that the server operator is in control of the domain
> name to be included in the certificate. Dependant on the type of
> certificate ordered, other checks may also be performed to verify the
> identity of the server operator. Finally the CA will issue the
> certificate which itself will be digitally signed by the CA. |
> 
> There is also a footnote which says:
> 
> |CAs can be privately run and purely internal to an organisation; or they
> could be public. Which type is most appropriate will depend on what the
> certificte will be used for. There are many public CAs available. A
> simple search in your search engine of choice should turn up lots of
> links. Most charge a fee for issuing a certificate. |
> 
> Does that address your concern?

Works for me, at this introductory stage.

At some more advanced point a discussion of the chain-of-trust issues
with x.509 might be appropriate, but this new wording at least avoids
implying that one must use a proprietary commercial CA.

-Steve M.

## 

Steve Marquess
OpenSSL Software Foundation, Inc.
1829 Mount Ephraim Road
Adamstown, MD  21710
USA
+1 877 673 6775 s/b
+1 301 874 2571 direct
marquess@opensslfoundation.com
marquess@openssl.com
gpg/pgp key: http://openssl.com/docs/0x6D1892F5.asc

**Comment by mattcaswell** [comment]
Closing issue.
